### ISSUE TITLE
Why value range 0-1?

### ISSUE THREAD

**Issue by Barteks2x** [flow/noise#14]
Why flow noise has value range 0-1? Why not leave it as -1 to 1? 

This value range is very counterintuitive when using it for terrain generation, and annoying to work with, where the average value specifies average terrain height (especially when used as 3d noise):
 * Scaling the noise generator output changes average value 
 * Changing almost any parameters when using multiple octaves (except frequency) changes average value

With value range 0-1, there is a very simple way to make 3d noise based terrain generator: multiply the noise output by desired height variation, add average height, and use the output as "heightmap" that also depends on height. 

The only situation I see where values 0 to 1 are simpler is when outputting to image, which is done only sometimes for testing. And when using noise output for interpolation, where it can be easily changed into 0-1 range.

**Comment by DDoS** [comment]
Try using negative values with any moderately complex curve, it sucks. Even x^2 doesn't work. If you want negative values then just use a scale bias and module.

**Comment by Barteks2x** [comment]
I don't see why it wouldn't work, especially after looking at `Curve` class.

**Comment by DDoS** [comment]
Negative values are less intuitive. They don't scale like you'd of expect. If you scale a module with output in the range [-1, 1] by 3, the new range has length 6. If it is in the range [0, 1], the length is 3. Obviously the latter is makes more sense.

You can apply a x^n function to a module output to bias it. Using n > 1 biases towards lower values, which is a more natural distribution. But if n is even, then negative values become positive, which you don't want. The original implementation would change the range to [0, 1], apply the exponent, then changed the range back to [-1, 1]. This reduced performance, so I modified the noise to output [0, 1], since it's simpler to process.

**Comment by Barteks2x** [comment]
So maybe the output range should at least be configurable in some way other than ScaleBias? Using ScaleBias for it requires calculating the actual min and max value, which depends on number of octaves and persistance (when using perlin module at least, and who knows what in other cases). It's a bit poinless to do work specifically to make value range 0 to 1 and then add a few octaves, and then reverse what has been done to make the range 0-1.

I also don't see how scaling to 0-1 and then back to -1 to 1 would affect performance when exponentials are involved, unless you use division instead of mutiplication.

And literally every other noise generation library I see gives output in range -1 to 1. So this one being different caused issues after switching to it. My terrain generator was broken for >1 year and I couldn't see what was wrong, because everything seemed right and yet the height was a bit wrong.
